### PR TITLE
add tailrec instance for either

### PR DESCRIPTION
**Pull request by jdegoes**

### CODE REVIEW

**Comment by paf31** [comment]
Have you verified that TCO fires on this code? It might be better to use `tailRec` just in case, since we've had issues with TCO and `case` in the past.

**Comment by jdegoes** [comment]
@paf31 Done!

**Comment by paf31** [comment]
Thanks! Looks good to me. @garyb Can we please include this in the next release candidate for 1.0?

**Comment by garyb** [comment]
Sure thing. I can get one out shortly as I think I've already done the dependencies of this.

**Comment by garyb** [comment]
Released as `v1.0.0-rc.2`

**Pull request merged**
